# 
# /*
#  * *********** WARNING **************
#  * This file generated by ModPerl::WrapXS/0.01
#  * Any changes made here will be lost
#  * ***********************************
#  * 01: lib/ModPerl/Code.pm:649
#  * 02: C:/MyFiles/modperl-2.0/lib/ModPerl/WrapXS.pm:620
#  * 03: C:/MyFiles/modperl-2.0/lib/ModPerl/WrapXS.pm:854
#  * 04: Makefile.PL:248
#  * 05: Makefile.PL:196
#  * 06: Makefile.PL:55
#  */
# 

package ModPerl::MethodLookup;

use strict;
use warnings;

my $methods = {
          'BINMODE' => [
                         [
                           'Apache::RequestIO',
                           'Apache::RequestRec'
                         ]
                       ],
          'CLEAR' => [
                       [
                         'APR::Table',
                         'APR::Table'
                       ]
                     ],
          'CLOSE' => [
                       [
                         'Apache::RequestIO',
                         'Apache::RequestRec'
                       ]
                     ],
          'DELETE' => [
                        [
                          'APR::Table',
                          'APR::Table'
                        ]
                      ],
          'DESTROY' => [
                         [
                           'APR::ThreadMutex',
                           'APR::ThreadMutex'
                         ],
                         [
                           'Apache::SubRequest',
                           'Apache::SubRequest'
                         ]
                       ],
          'EXISTS' => [
                        [
                          'APR::Table',
                          'APR::Table'
                        ]
                      ],
          'FETCH' => [
                       [
                         'APR::Table',
                         'APR::Table'
                       ]
                     ],
          'FILENO' => [
                        [
                          'Apache::RequestIO',
                          'Apache::RequestRec'
                        ]
                      ],
          'FIRSTKEY' => [
                          [
                            'APR::Table',
                            'APR::Table'
                          ]
                        ],
          'GETC' => [
                      [
                        'Apache::RequestIO',
                        'Apache::RequestRec'
                      ]
                    ],
          'NEXTKEY' => [
                         [
                           'APR::Table',
                           'APR::Table'
                         ]
                       ],
          'OPEN' => [
                      [
                        'Apache::RequestIO',
                        'Apache::RequestRec'
                      ]
                    ],
          'PRINT' => [
                       [
                         'Apache::RequestIO',
                         'Apache::RequestRec'
                       ],
                       [
                         'Apache::Filter',
                         'Apache::Filter'
                       ]
                     ],
          'PRINTF' => [
                        [
                          'Apache::RequestIO',
                          'Apache::RequestRec'
                        ]
                      ],
          'READ' => [
                      [
                        'Apache::RequestIO',
                        'Apache::RequestRec'
                      ]
                    ],
          'STORE' => [
                       [
                         'APR::Table',
                         'APR::Table'
                       ]
                     ],
          'TIEHANDLE' => [
                           [
                             'Apache::RequestIO',
                             'Apache::RequestRec'
                           ],
                           [
                             'Apache::Filter',
                             'Apache::Filter'
                           ]
                         ],
          'UNTIE' => [
                       [
                         'Apache::RequestIO',
                         'Apache::RequestRec'
                       ]
                     ],
          'WRITE' => [
                       [
                         'Apache::RequestIO',
                         'Apache::RequestRec'
                       ]
                     ],
          'aborted' => [
                         [
                           'Apache::Connection',
                           'Apache::Connection'
                         ]
                       ],
          'add' => [
                     [
                       'APR::Table',
                       'APR::Table'
                     ]
                   ],
          'add_config' => [
                            [
                              'Apache::ServerUtil',
                              'Apache::Server'
                            ],
                            [
                              'Apache::RequestUtil',
                              'Apache::RequestRec'
                            ]
                          ],
          'add_input_filter' => [
                                  [
                                    'Apache::Filter',
                                    'Apache::RequestRec'
                                  ],
                                  [
                                    'Apache::Filter',
                                    'Apache::Connection'
                                  ]
                                ],
          'add_output_filter' => [
                                   [
                                     'Apache::Filter',
                                     'Apache::RequestRec'
                                   ],
                                   [
                                     'Apache::Filter',
                                     'Apache::Connection'
                                   ]
                                 ],
          'add_version_component' => [
                                       [
                                         'Apache::ServerUtil',
                                         'Apache'
                                       ]
                                     ],
          'addrs' => [
                       [
                         'Apache::Server',
                         'Apache::Server'
                       ]
                     ],
          'allow_methods' => [
                               [
                                 'Apache::Access',
                                 'Apache::RequestRec'
                               ]
                             ],
          'allow_options' => [
                               [
                                 'Apache::Access',
                                 'Apache::RequestRec'
                               ]
                             ],
          'allow_overrides' => [
                                 [
                                   'Apache::Access',
                                   'Apache::RequestRec'
                                 ]
                               ],
          'allowed' => [
                         [
                           'Apache::RequestRec',
                           'Apache::RequestRec'
                         ]
                       ],
          'allowed_methods' => [
                                 [
                                   'Apache::RequestRec',
                                   'Apache::RequestRec'
                                 ]
                               ],
          'allowed_xmethods' => [
                                  [
                                    'Apache::RequestRec',
                                    'Apache::RequestRec'
                                  ]
                                ],
          'ap_auth_type' => [
                              [
                                'Apache::RequestRec',
                                'Apache::RequestRec'
                              ]
                            ],
          'args' => [
                      [
                        'Apache::Directive',
                        'Apache::Directive'
                      ],
                      [
                        'Apache::RequestRec',
                        'Apache::RequestRec'
                      ]
                    ],
          'args_how' => [
                          [
                            'Apache::Command',
                            'Apache::Command'
                          ]
                        ],
          'as_hash' => [
                         [
                           'Apache::Directive',
                           'Apache::Directive'
                         ]
                       ],
          'as_string' => [
                           [
                             'Apache::RequestUtil',
                             'Apache::RequestRec'
                           ],
                           [
                             'Apache::Directive',
                             'Apache::Directive'
                           ]
                         ],
          'assbackwards' => [
                              [
                                'Apache::RequestRec',
                                'Apache::RequestRec'
                              ]
                            ],
          'auth_name' => [
                           [
                             'Apache::Access',
                             'Apache::RequestRec'
                           ]
                         ],
          'auth_type' => [
                           [
                             'Apache::Access',
                             'Apache::RequestRec'
                           ]
                         ],
          'base_server' => [
                             [
                               'Apache::Connection',
                               'Apache::Connection'
                             ]
                           ],
          'bind' => [
                      [
                        'APR::Socket',
                        'APR::Socket'
                      ]
                    ],
          'bucket_alloc' => [
                              [
                                'Apache::Connection',
                                'Apache::Connection'
                              ]
                            ],
          'bytes_sent' => [
                            [
                              'Apache::RequestRec',
                              'Apache::RequestRec'
                            ]
                          ],
          'c' => [
                   [
                     'Apache::Filter',
                     'Apache::Filter'
                   ]
                 ],
          'canonical_filename' => [
                                    [
                                      'Apache::RequestRec',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'check_cmd_context' => [
                                   [
                                     'Apache::Command',
                                     'Apache::Command'
                                   ]
                                 ],
          'cleanup_for_exec' => [
                                  [
                                    'APR::Pool',
                                    'APR::Pool'
                                  ]
                                ],
          'cleanup_register' => [
                                  [
                                    'APR::Pool',
                                    'APR::Pool'
                                  ]
                                ],
          'clear' => [
                       [
                         'APR::Table',
                         'APR::Table'
                       ],
                       [
                         'APR::Pool',
                         'APR::Pool'
                       ]
                     ],
          'client_socket' => [
                               [
                                 'Apache::Connection',
                                 'Apache::Connection'
                               ]
                             ],
          'close' => [
                       [
                         'APR::Socket',
                         'APR::Socket'
                       ]
                     ],
          'cmd' => [
                     [
                       'Apache::CmdParms',
                       'Apache::CmdParms'
                     ]
                   ],
          'cmd_data' => [
                          [
                            'Apache::Command',
                            'Apache::Command'
                          ]
                        ],
          'cmds' => [
                      [
                        'Apache::Module',
                        'Apache::Module'
                      ]
                    ],
          'concat' => [
                        [
                          'APR::Brigade',
                          'APR::Brigade'
                        ]
                      ],
          'config_file' => [
                             [
                               'Apache::CmdParms',
                               'Apache::CmdParms'
                             ]
                           ],
          'conftree' => [
                          [
                            'Apache::Directive',
                            'Apache::Directive'
                          ]
                        ],
          'conn_config' => [
                             [
                               'Apache::Connection',
                               'Apache::Connection'
                             ]
                           ],
          'connect' => [
                         [
                           'APR::Socket',
                           'APR::Socket'
                         ]
                       ],
          'connection' => [
                            [
                              'Apache::RequestRec',
                              'Apache::RequestRec'
                            ]
                          ],
          'construct_server' => [
                                  [
                                    'Apache::URI',
                                    'Apache::RequestRec'
                                  ]
                                ],
          'construct_url' => [
                               [
                                 'Apache::URI',
                                 'Apache::RequestRec'
                               ]
                             ],
          'content_encoding' => [
                                  [
                                    'Apache::RequestRec',
                                    'Apache::RequestRec'
                                  ]
                                ],
          'content_languages' => [
                                   [
                                     'Apache::RequestRec',
                                     'Apache::RequestRec'
                                   ]
                                 ],
          'content_type' => [
                              [
                                'Apache::RequestRec',
                                'Apache::RequestRec'
                              ]
                            ],
          'context' => [
                         [
                           'Apache::CmdParms',
                           'Apache::CmdParms'
                         ]
                       ],
          'copy' => [
                      [
                        'APR::Table',
                        'APR::Table'
                      ]
                    ],
          'ctx' => [
                     [
                       'Apache::Filter',
                       'Apache::Filter'
                     ]
                   ],
          'current_callback' => [
                                  [
                                    'ModPerl::Util',
                                    'Apache'
                                  ]
                                ],
          'custom_response' => [
                                 [
                                   'Apache::Response',
                                   'Apache::RequestRec'
                                 ]
                               ],
          'data' => [
                      [
                        'APR::Bucket',
                        'APR::Bucket'
                      ],
                      [
                        'Apache::Directive',
                        'Apache::Directive'
                      ]
                    ],
          'default_port_for_scheme' => [
                                         [
                                           'APR::URI',
                                           'APR::URI'
                                         ]
                                       ],
          'default_type' => [
                              [
                                'Apache::RequestUtil',
                                'Apache::RequestRec'
                              ]
                            ],
          'destroy' => [
                         [
                           'APR::Brigade',
                           'APR::Brigade'
                         ],
                         [
                           'APR::Pool',
                           'APR::Pool'
                         ]
                       ],
          'die' => [
                     [
                       'Apache::HookRun',
                       'Apache::RequestRec'
                     ]
                   ],
          'dir_config' => [
                            [
                              'Apache::ServerUtil',
                              'Apache::Server'
                            ],
                            [
                              'Apache::RequestUtil',
                              'Apache::RequestRec'
                            ]
                          ],
          'directive' => [
                           [
                             'Apache::CmdParms',
                             'Apache::CmdParms'
                           ],
                           [
                             'Apache::Directive',
                             'Apache::Directive'
                           ]
                         ],
          'discard_request_body' => [
                                      [
                                        'Apache::RequestIO',
                                        'Apache::RequestRec'
                                      ]
                                    ],
          'dns_looked_up' => [
                               [
                                 'APR::URI',
                                 'APR::URI'
                               ]
                             ],
          'dns_resolved' => [
                              [
                                'APR::URI',
                                'APR::URI'
                              ]
                            ],
          'do' => [
                    [
                      'APR::Table',
                      'APR::Table'
                    ]
                  ],
          'document_root' => [
                               [
                                 'Apache::RequestUtil',
                                 'Apache::RequestRec'
                               ]
                             ],
          'dynamic_load_handle' => [
                                     [
                                       'Apache::Module',
                                       'Apache::Module'
                                     ]
                                   ],
          'empty' => [
                       [
                         'APR::Brigade',
                         'APR::Brigade'
                       ]
                     ],
          'encode_len' => [
                            [
                              'APR::Base64',
                              'APR::Base64'
                            ]
                          ],
          'eos_create' => [
                            [
                              'APR::Bucket',
                              'APR::Bucket'
                            ]
                          ],
          'equal' => [
                       [
                         'APR::SockAddr',
                         'APR::SockAddr'
                       ]
                     ],
          'err_directive' => [
                               [
                                 'Apache::CmdParms',
                                 'Apache::CmdParms'
                               ]
                             ],
          'err_headers_out' => [
                                 [
                                   'Apache::RequestRec',
                                   'Apache::RequestRec'
                                 ]
                               ],
          'errmsg' => [
                        [
                          'Apache::Command',
                          'Apache::Command'
                        ]
                      ],
          'error_fname' => [
                             [
                               'Apache::Server',
                               'Apache::Server'
                             ]
                           ],
          'error_log2stderr' => [
                                  [
                                    'Apache::ServerUtil',
                                    'Apache::Server'
                                  ]
                                ],
          'escape_path' => [
                             [
                               'Apache::Util',
                               'Apache::Util'
                             ]
                           ],
          'exists_config_define' => [
                                      [
                                        'Apache::ServerUtil',
                                        'Apache'
                                      ]
                                    ],
          'exit' => [
                      [
                        'ModPerl::Util',
                        'ModPerl::Util'
                      ]
                    ],
          'fflush' => [
                        [
                          'Apache::Filter',
                          'Apache::Filter'
                        ]
                      ],
          'filename' => [
                          [
                            'Apache::Directive',
                            'Apache::Directive'
                          ],
                          [
                            'Apache::RequestRec',
                            'Apache::RequestRec'
                          ]
                        ],
          'filename_of_pathname' => [
                                      [
                                        'APR::Util',
                                        'APR'
                                      ]
                                    ],
          'filter_flush' => [
                              [
                                'Apache::Filter',
                                'APR::Brigade'
                              ]
                            ],
          'find_linked_module' => [
                                    [
                                      'Apache::Module',
                                      'Apache::Module'
                                    ]
                                  ],
          'find_module_name' => [
                                  [
                                    'Apache::Module',
                                    'Apache::Module'
                                  ]
                                ],
          'first' => [
                       [
                         'APR::Brigade',
                         'APR::Brigade'
                       ]
                     ],
          'first_child' => [
                             [
                               'Apache::Directive',
                               'Apache::Directive'
                             ]
                           ],
          'flush_create' => [
                              [
                                'APR::Bucket',
                                'APR::Bucket'
                              ]
                            ],
          'format_size' => [
                             [
                               'APR::String',
                               'APR::String'
                             ]
                           ],
          'format_time' => [
                             [
                               'Apache::Util',
                               'Apache::Util'
                             ]
                           ],
          'fputs' => [
                       [
                         'Apache::Filter',
                         'Apache::Filter'
                       ]
                     ],
          'fragment' => [
                          [
                            'APR::URI',
                            'APR::URI'
                          ]
                        ],
          'frec' => [
                      [
                        'Apache::Filter',
                        'Apache::Filter'
                      ]
                    ],
          'get_brigade' => [
                             [
                               'Apache::Filter',
                               'Apache::Filter'
                             ]
                           ],
          'get_client_block' => [
                                  [
                                    'Apache::RequestIO',
                                    'Apache::RequestRec'
                                  ]
                                ],
          'get_config' => [
                            [
                              'Apache::Module',
                              'Apache::Module'
                            ]
                          ],
          'get_handlers' => [
                              [
                                'Apache::ServerUtil',
                                'Apache::Server'
                              ],
                              [
                                'Apache::RequestUtil',
                                'Apache::RequestRec'
                              ]
                            ],
          'get_limit_req_body' => [
                                    [
                                      'Apache::RequestUtil',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'get_parent' => [
                            [
                              'APR::Pool',
                              'APR::Pool'
                            ]
                          ],
          'get_remote_host' => [
                                 [
                                   'Apache::Connection',
                                   'Apache::Connection'
                                 ]
                               ],
          'get_remote_logname' => [
                                    [
                                      'Apache::Access',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'get_server_built' => [
                                  [
                                    'Apache::ServerUtil',
                                    'Apache'
                                  ]
                                ],
          'get_server_name' => [
                                 [
                                   'Apache::RequestUtil',
                                   'Apache::RequestRec'
                                 ]
                               ],
          'get_server_port' => [
                                 [
                                   'Apache::RequestUtil',
                                   'Apache::RequestRec'
                                 ]
                               ],
          'get_server_version' => [
                                    [
                                      'Apache::ServerUtil',
                                      'Apache'
                                    ]
                                  ],
          'get_status_line' => [
                                 [
                                   'Apache::RequestUtil',
                                   'Apache'
                                 ]
                               ],
          'handler' => [
                         [
                           'Apache::RequestRec',
                           'Apache::RequestRec'
                         ]
                       ],
          'header_only' => [
                             [
                               'Apache::RequestRec',
                               'Apache::RequestRec'
                             ]
                           ],
          'headers_in' => [
                            [
                              'Apache::RequestRec',
                              'Apache::RequestRec'
                            ]
                          ],
          'headers_out' => [
                             [
                               'Apache::RequestRec',
                               'Apache::RequestRec'
                             ]
                           ],
          'hostinfo' => [
                          [
                            'APR::URI',
                            'APR::URI'
                          ]
                        ],
          'hostname' => [
                          [
                            'APR::URI',
                            'APR::URI'
                          ],
                          [
                            'Apache::RequestRec',
                            'Apache::RequestRec'
                          ]
                        ],
          'id' => [
                    [
                      'Apache::Connection',
                      'Apache::Connection'
                    ]
                  ],
          'info' => [
                      [
                        'Apache::CmdParms',
                        'Apache::CmdParms'
                      ]
                    ],
          'input_filters' => [
                               [
                                 'Apache::Connection',
                                 'Apache::Connection'
                               ],
                               [
                                 'Apache::RequestRec',
                                 'Apache::RequestRec'
                               ]
                             ],
          'insert_after' => [
                              [
                                'APR::Bucket',
                                'APR::Bucket'
                              ]
                            ],
          'insert_before' => [
                               [
                                 'APR::Bucket',
                                 'APR::Bucket'
                               ]
                             ],
          'insert_head' => [
                             [
                               'APR::Brigade',
                               'APR::Brigade'
                             ]
                           ],
          'insert_tail' => [
                             [
                               'APR::Brigade',
                               'APR::Brigade'
                             ]
                           ],
          'internal_fast_redirect' => [
                                        [
                                          'Apache::SubRequest',
                                          'Apache::RequestRec'
                                        ]
                                      ],
          'internal_redirect' => [
                                   [
                                     'Apache::SubRequest',
                                     'Apache::RequestRec'
                                   ]
                                 ],
          'internal_redirect_handler' => [
                                           [
                                             'Apache::SubRequest',
                                             'Apache::RequestRec'
                                           ]
                                         ],
          'ip_get' => [
                        [
                          'APR::SockAddr',
                          'APR::SockAddr'
                        ]
                      ],
          'ip_set' => [
                        [
                          'APR::SockAddr',
                          'APR::SockAddr'
                        ]
                      ],
          'is_ancestor' => [
                             [
                               'APR::Pool',
                               'APR::Pool'
                             ]
                           ],
          'is_eos' => [
                        [
                          'APR::Bucket',
                          'APR::Bucket'
                        ]
                      ],
          'is_flush' => [
                          [
                            'APR::Bucket',
                            'APR::Bucket'
                          ]
                        ],
          'is_initial_req' => [
                                [
                                  'Apache::RequestUtil',
                                  'Apache::RequestRec'
                                ]
                              ],
          'is_initialized' => [
                                [
                                  'APR::URI',
                                  'APR::URI'
                                ]
                              ],
          'is_virtual' => [
                            [
                              'Apache::Server',
                              'Apache::Server'
                            ]
                          ],
          'keep_alive' => [
                            [
                              'Apache::Server',
                              'Apache::Server'
                            ]
                          ],
          'keep_alive_max' => [
                                [
                                  'Apache::Server',
                                  'Apache::Server'
                                ]
                              ],
          'keep_alive_timeout' => [
                                    [
                                      'Apache::Server',
                                      'Apache::Server'
                                    ]
                                  ],
          'keepalive' => [
                           [
                             'Apache::Connection',
                             'Apache::Connection'
                           ]
                         ],
          'last' => [
                      [
                        'APR::Brigade',
                        'APR::Brigade'
                      ]
                    ],
          'length' => [
                        [
                          'APR::Bucket',
                          'APR::Bucket'
                        ]
                      ],
          'limit_req_fields' => [
                                  [
                                    'Apache::Server',
                                    'Apache::Server'
                                  ]
                                ],
          'limit_req_fieldsize' => [
                                     [
                                       'Apache::Server',
                                       'Apache::Server'
                                     ]
                                   ],
          'limit_req_line' => [
                                [
                                  'Apache::Server',
                                  'Apache::Server'
                                ]
                              ],
          'limited' => [
                         [
                           'Apache::CmdParms',
                           'Apache::CmdParms'
                         ]
                       ],
          'limited_xmethods' => [
                                  [
                                    'Apache::CmdParms',
                                    'Apache::CmdParms'
                                  ]
                                ],
          'line_num' => [
                          [
                            'Apache::Directive',
                            'Apache::Directive'
                          ]
                        ],
          'listen' => [
                        [
                          'APR::Socket',
                          'APR::Socket'
                        ]
                      ],
          'loaded' => [
                        [
                          'Apache::Module',
                          'Apache::Module'
                        ]
                      ],
          'local_addr' => [
                            [
                              'Apache::Connection',
                              'Apache::Connection'
                            ]
                          ],
          'local_host' => [
                            [
                              'Apache::Connection',
                              'Apache::Connection'
                            ]
                          ],
          'local_ip' => [
                          [
                            'Apache::Connection',
                            'Apache::Connection'
                          ]
                        ],
          'location' => [
                          [
                            'Apache::RequestUtil',
                            'Apache::RequestRec'
                          ]
                        ],
          'location_merge' => [
                                [
                                  'Apache::RequestUtil',
                                  'Apache::RequestRec'
                                ]
                              ],
          'lock' => [
                      [
                        'APR::ThreadMutex',
                        'APR::ThreadMutex'
                      ]
                    ],
          'log' => [
                     [
                       'Apache::Log',
                       'Apache::Server'
                     ],
                     [
                       'Apache::Log',
                       'Apache::RequestRec'
                     ]
                   ],
          'log_pid' => [
                         [
                           'Apache::Log',
                           'Apache'
                         ]
                       ],
          'loglevel' => [
                          [
                            'Apache::Server',
                            'Apache::Server'
                          ]
                        ],
          'lookup_defaults' => [
                                 [
                                   'Apache::Server',
                                   'Apache::Server'
                                 ]
                               ],
          'lookup_dirent' => [
                               [
                                 'Apache::SubRequest',
                                 'Apache::RequestRec'
                               ]
                             ],
          'lookup_file' => [
                             [
                               'Apache::SubRequest',
                               'Apache::RequestRec'
                             ]
                           ],
          'lookup_method_uri' => [
                                   [
                                     'Apache::SubRequest',
                                     'Apache::RequestRec'
                                   ]
                                 ],
          'lookup_uri' => [
                            [
                              'Apache::SubRequest',
                              'Apache::RequestRec'
                            ]
                          ],
          'main' => [
                      [
                        'Apache::RequestRec',
                        'Apache::RequestRec'
                      ]
                    ],
          'make' => [
                      [
                        'APR::Table',
                        'APR::Table'
                      ]
                    ],
          'make_etag' => [
                           [
                             'Apache::Response',
                             'Apache::RequestRec'
                           ]
                         ],
          'meets_conditions' => [
                                  [
                                    'Apache::Response',
                                    'Apache::RequestRec'
                                  ]
                                ],
          'merge' => [
                       [
                         'APR::Table',
                         'APR::Table'
                       ]
                     ],
          'method' => [
                        [
                          'Apache::RequestRec',
                          'Apache::RequestRec'
                        ]
                      ],
          'method_number' => [
                               [
                                 'Apache::RequestRec',
                                 'Apache::RequestRec'
                               ]
                             ],
          'method_register' => [
                                 [
                                   'Apache::RequestUtil',
                                   'Apache'
                                 ]
                               ],
          'minor_version' => [
                               [
                                 'Apache::Module',
                                 'Apache::Module'
                               ]
                             ],
          'module_config' => [
                               [
                                 'Apache::Server',
                                 'Apache::Server'
                               ]
                             ],
          'module_index' => [
                              [
                                'Apache::Module',
                                'Apache::Module'
                              ]
                            ],
          'mtime' => [
                       [
                         'Apache::RequestRec',
                         'Apache::RequestRec'
                       ]
                     ],
          'name' => [
                      [
                        'APR::Bucket',
                        'APR::BucketType'
                      ],
                      [
                        'Apache::FilterRec',
                        'Apache::FilterRec'
                      ],
                      [
                        'Apache::Module',
                        'Apache::Module'
                      ],
                      [
                        'Apache::Command',
                        'Apache::Command'
                      ]
                    ],
          'names' => [
                       [
                         'Apache::Server',
                         'Apache::Server'
                       ]
                     ],
          'new' => [
                     [
                       'APR::Bucket',
                       'APR::Bucket'
                     ],
                     [
                       'APR::NetLib',
                       'APR::IpSubnet'
                     ],
                     [
                       'APR::UUID',
                       'APR::UUID'
                     ],
                     [
                       'Apache::RequestUtil',
                       'Apache::RequestRec'
                     ],
                     [
                       'APR::Brigade',
                       'APR::Brigade'
                     ],
                     [
                       'APR::ThreadMutex',
                       'APR::ThreadMutex'
                     ],
                     [
                       'APR::Pool',
                       'APR::Pool'
                     ]
                   ],
          'next' => [
                      [
                        'Apache::FilterRec',
                        'Apache::FilterRec'
                      ],
                      [
                        'Apache::Server',
                        'Apache::Server'
                      ],
                      [
                        'Apache::Module',
                        'Apache::Module'
                      ],
                      [
                        'APR::Brigade',
                        'APR::Brigade'
                      ],
                      [
                        'Apache::Command',
                        'Apache::Command'
                      ],
                      [
                        'Apache::Directive',
                        'Apache::Directive'
                      ],
                      [
                        'Apache::RequestRec',
                        'Apache::RequestRec'
                      ],
                      [
                        'Apache::Filter',
                        'Apache::Filter'
                      ]
                    ],
          'no_cache' => [
                          [
                            'Apache::RequestUtil',
                            'Apache::RequestRec'
                          ]
                        ],
          'no_local_copy' => [
                               [
                                 'Apache::RequestRec',
                                 'Apache::RequestRec'
                               ]
                             ],
          'note_auth_failure' => [
                                   [
                                     'Apache::Access',
                                     'Apache::RequestRec'
                                   ]
                                 ],
          'note_basic_auth_failure' => [
                                         [
                                           'Apache::Access',
                                           'Apache::RequestRec'
                                         ]
                                       ],
          'note_digest_auth_failure' => [
                                          [
                                            'Apache::Access',
                                            'Apache::RequestRec'
                                          ]
                                        ],
          'notes' => [
                       [
                         'Apache::Connection',
                         'Apache::Connection'
                       ],
                       [
                         'Apache::RequestRec',
                         'Apache::RequestRec'
                       ]
                     ],
          'opt_get' => [
                         [
                           'APR::Socket',
                           'APR::Socket'
                         ]
                       ],
          'opt_set' => [
                         [
                           'APR::Socket',
                           'APR::Socket'
                         ]
                       ],
          'output_filters' => [
                                [
                                  'Apache::Connection',
                                  'Apache::Connection'
                                ],
                                [
                                  'Apache::RequestRec',
                                  'Apache::RequestRec'
                                ]
                              ],
          'overlap' => [
                         [
                           'APR::Table',
                           'APR::Table'
                         ]
                       ],
          'overlay' => [
                         [
                           'APR::Table',
                           'APR::Table'
                         ]
                       ],
          'override' => [
                          [
                            'Apache::CmdParms',
                            'Apache::CmdParms'
                          ]
                        ],
          'parent' => [
                        [
                          'Apache::Directive',
                          'Apache::Directive'
                        ]
                      ],
          'parse' => [
                       [
                         'APR::UUID',
                         'APR::UUID'
                       ],
                       [
                         'APR::URI',
                         'APR::URI'
                       ]
                     ],
          'parse_http' => [
                            [
                              'APR::Date',
                              'APR::Date'
                            ]
                          ],
          'parse_rfc' => [
                           [
                             'APR::Date',
                             'APR::Date'
                           ]
                         ],
          'parse_uri' => [
                           [
                             'Apache::URI',
                             'Apache::RequestRec'
                           ]
                         ],
          'parsed_uri' => [
                            [
                              'Apache::URI',
                              'Apache::RequestRec'
                            ]
                          ],
          'pass_brigade' => [
                              [
                                'Apache::Filter',
                                'Apache::Filter'
                              ]
                            ],
          'password' => [
                          [
                            'APR::URI',
                            'APR::URI'
                          ]
                        ],
          'password_get' => [
                              [
                                'APR::Util',
                                'APR'
                              ]
                            ],
          'password_validate' => [
                                   [
                                     'APR::Util',
                                     'APR'
                                   ]
                                 ],
          'path' => [
                      [
                        'Apache::CmdParms',
                        'Apache::CmdParms'
                      ],
                      [
                        'Apache::Server',
                        'Apache::Server'
                      ],
                      [
                        'APR::URI',
                        'APR::URI'
                      ]
                    ],
          'path_info' => [
                           [
                             'Apache::RequestRec',
                             'Apache::RequestRec'
                           ]
                         ],
          'pconf' => [
                       [
                         'Apache::Process',
                         'Apache::Process'
                       ]
                     ],
          'per_dir_config' => [
                                [
                                  'Apache::RequestRec',
                                  'Apache::RequestRec'
                                ]
                              ],
          'pnotes' => [
                        [
                          'Apache::RequestUtil',
                          'Apache::RequestRec'
                        ]
                      ],
          'pool' => [
                      [
                        'Apache::CmdParms',
                        'Apache::CmdParms'
                      ],
                      [
                        'Apache::Connection',
                        'Apache::Connection'
                      ],
                      [
                        'Apache::Process',
                        'Apache::Process'
                      ],
                      [
                        'Apache::RequestRec',
                        'Apache::RequestRec'
                      ]
                    ],
          'pool_get' => [
                          [
                            'APR::ThreadMutex',
                            'APR::ThreadMutex'
                          ]
                        ],
          'port' => [
                      [
                        'Apache::Server',
                        'Apache::Server'
                      ],
                      [
                        'APR::URI',
                        'APR::URI'
                      ]
                    ],
          'port_get' => [
                          [
                            'APR::SockAddr',
                            'APR::SockAddr'
                          ]
                        ],
          'port_set' => [
                          [
                            'APR::SockAddr',
                            'APR::SockAddr'
                          ]
                        ],
          'prev' => [
                      [
                        'APR::Brigade',
                        'APR::Brigade'
                      ],
                      [
                        'Apache::RequestRec',
                        'Apache::RequestRec'
                      ]
                    ],
          'print' => [
                       [
                         'Apache::RequestIO',
                         'Apache::RequestRec'
                       ],
                       [
                         'Apache::Filter',
                         'Apache::Filter'
                       ]
                     ],
          'printf' => [
                        [
                          'Apache::RequestIO',
                          'Apache::RequestRec'
                        ]
                      ],
          'process' => [
                         [
                           'Apache::Server',
                           'Apache::Server'
                         ]
                       ],
          'proto_input_filters' => [
                                     [
                                       'Apache::RequestRec',
                                       'Apache::RequestRec'
                                     ]
                                   ],
          'proto_num' => [
                           [
                             'Apache::RequestRec',
                             'Apache::RequestRec'
                           ]
                         ],
          'proto_output_filters' => [
                                      [
                                        'Apache::RequestRec',
                                        'Apache::RequestRec'
                                      ]
                                    ],
          'protocol' => [
                          [
                            'Apache::RequestRec',
                            'Apache::RequestRec'
                          ]
                        ],
          'proxyreq' => [
                          [
                            'Apache::RequestRec',
                            'Apache::RequestRec'
                          ]
                        ],
          'psignature' => [
                            [
                              'Apache::ServerUtil',
                              'Apache::RequestRec'
                            ]
                          ],
          'push_handlers' => [
                               [
                                 'Apache::ServerUtil',
                                 'Apache::Server'
                               ],
                               [
                                 'Apache::RequestUtil',
                                 'Apache::RequestRec'
                               ]
                             ],
          'puts' => [
                      [
                        'Apache::RequestIO',
                        'Apache::RequestRec'
                      ]
                    ],
          'query' => [
                       [
                         'APR::URI',
                         'APR::URI'
                       ]
                     ],
          'r' => [
                   [
                     'Apache::Filter',
                     'Apache::Filter'
                   ]
                 ],
          'rationalize_mtime' => [
                                   [
                                     'Apache::Response',
                                     'Apache::RequestRec'
                                   ]
                                 ],
          'read' => [
                      [
                        'APR::Bucket',
                        'APR::Bucket'
                      ],
                      [
                        'Apache::RequestIO',
                        'Apache::RequestRec'
                      ],
                      [
                        'Apache::Filter',
                        'Apache::Filter'
                      ]
                    ],
          'recv' => [
                      [
                        'APR::Socket',
                        'APR::Socket'
                      ]
                    ],
          'recvfrom' => [
                          [
                            'APR::Socket',
                            'APR::Socket'
                          ]
                        ],
          'remaining' => [
                           [
                             'Apache::RequestRec',
                             'Apache::RequestRec'
                           ]
                         ],
          'remote_addr' => [
                             [
                               'Apache::Connection',
                               'Apache::Connection'
                             ]
                           ],
          'remote_host' => [
                             [
                               'Apache::Connection',
                               'Apache::Connection'
                             ]
                           ],
          'remote_ip' => [
                           [
                             'Apache::Connection',
                             'Apache::Connection'
                           ]
                         ],
          'remote_logname' => [
                                [
                                  'Apache::Connection',
                                  'Apache::Connection'
                                ]
                              ],
          'remove' => [
                        [
                          'APR::Bucket',
                          'APR::Bucket'
                        ],
                        [
                          'Apache::Filter',
                          'Apache::Filter'
                        ]
                      ],
          'remove_input_filter' => [
                                     [
                                       'Apache::Filter',
                                       'Apache::Filter'
                                     ]
                                   ],
          'remove_loaded_module' => [
                                      [
                                        'Apache::Module',
                                        'Apache::Module'
                                      ]
                                    ],
          'remove_module' => [
                               [
                                 'Apache::Module',
                                 'Apache::Module'
                               ]
                             ],
          'remove_output_filter' => [
                                      [
                                        'Apache::Filter',
                                        'Apache::Filter'
                                      ]
                                    ],
          'req_override' => [
                              [
                                'Apache::Command',
                                'Apache::Command'
                              ]
                            ],
          'request' => [
                         [
                           'Apache::RequestUtil',
                           'Apache'
                         ]
                       ],
          'request_config' => [
                                [
                                  'Apache::RequestRec',
                                  'Apache::RequestRec'
                                ]
                              ],
          'request_time' => [
                              [
                                'Apache::RequestRec',
                                'Apache::RequestRec'
                              ]
                            ],
          'requires' => [
                          [
                            'Apache::Access',
                            'Apache::RequestRec'
                          ]
                        ],
          'rflush' => [
                        [
                          'Apache::RequestIO',
                          'Apache::RequestRec'
                        ]
                      ],
          'run' => [
                     [
                       'Apache::SubRequest',
                       'Apache::SubRequest'
                     ]
                   ],
          'run_access_checker' => [
                                    [
                                      'Apache::HookRun',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'run_auth_checker' => [
                                  [
                                    'Apache::HookRun',
                                    'Apache::RequestRec'
                                  ]
                                ],
          'run_check_user_id' => [
                                   [
                                     'Apache::HookRun',
                                     'Apache::RequestRec'
                                   ]
                                 ],
          'run_create_request' => [
                                    [
                                      'Apache::HookRun',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'run_fixups' => [
                            [
                              'Apache::HookRun',
                              'Apache::RequestRec'
                            ]
                          ],
          'run_handler' => [
                             [
                               'Apache::HookRun',
                               'Apache::RequestRec'
                             ]
                           ],
          'run_header_parser' => [
                                   [
                                     'Apache::HookRun',
                                     'Apache::RequestRec'
                                   ]
                                 ],
          'run_log_transaction' => [
                                     [
                                       'Apache::HookRun',
                                       'Apache::RequestRec'
                                     ]
                                   ],
          'run_map_to_storage' => [
                                    [
                                      'Apache::HookRun',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'run_post_read_request' => [
                                       [
                                         'Apache::HookRun',
                                         'Apache::RequestRec'
                                       ]
                                     ],
          'run_translate_name' => [
                                    [
                                      'Apache::HookRun',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'run_type_checker' => [
                                  [
                                    'Apache::HookRun',
                                    'Apache::RequestRec'
                                  ]
                                ],
          'satisfies' => [
                           [
                             'Apache::Access',
                             'Apache::RequestRec'
                           ]
                         ],
          'sbh' => [
                     [
                       'Apache::Connection',
                       'Apache::Connection'
                     ]
                   ],
          'scheme' => [
                        [
                          'APR::URI',
                          'APR::URI'
                        ]
                      ],
          'seen_eos' => [
                          [
                            'Apache::Filter',
                            'Apache::Filter'
                          ]
                        ],
          'send' => [
                      [
                        'APR::Socket',
                        'APR::Socket'
                      ]
                    ],
          'send_cgi_header' => [
                                 [
                                   'Apache::Response',
                                   'Apache::RequestRec'
                                 ]
                               ],
          'send_error_response' => [
                                     [
                                       'Apache::Response',
                                       'Apache::RequestRec'
                                     ]
                                   ],
          'send_mmap' => [
                           [
                             'Apache::Response',
                             'Apache::RequestRec'
                           ]
                         ],
          'sendfile' => [
                          [
                            'Apache::RequestIO',
                            'Apache::RequestRec'
                          ]
                        ],
          'sendto' => [
                        [
                          'APR::Socket',
                          'APR::Socket'
                        ]
                      ],
          'server' => [
                        [
                          'Apache::CmdParms',
                          'Apache::CmdParms'
                        ],
                        [
                          'Apache::ServerUtil',
                          'Apache'
                        ],
                        [
                          'Apache::RequestRec',
                          'Apache::RequestRec'
                        ]
                      ],
          'server_admin' => [
                              [
                                'Apache::Server',
                                'Apache::Server'
                              ]
                            ],
          'server_hostname' => [
                                 [
                                   'Apache::Server',
                                   'Apache::Server'
                                 ]
                               ],
          'server_root_relative' => [
                                      [
                                        'Apache::ServerUtil',
                                        'Apache'
                                      ]
                                    ],
          'set' => [
                     [
                       'APR::Table',
                       'APR::Table'
                     ]
                   ],
          'set_basic_credentials' => [
                                       [
                                         'Apache::RequestUtil',
                                         'Apache::RequestRec'
                                       ]
                                     ],
          'set_content_length' => [
                                    [
                                      'Apache::Response',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'set_etag' => [
                          [
                            'Apache::Response',
                            'Apache::RequestRec'
                          ]
                        ],
          'set_handlers' => [
                              [
                                'Apache::ServerUtil',
                                'Apache::Server'
                              ],
                              [
                                'Apache::RequestUtil',
                                'Apache::RequestRec'
                              ]
                            ],
          'set_keepalive' => [
                               [
                                 'Apache::Response',
                                 'Apache::RequestRec'
                               ]
                             ],
          'set_last_modified' => [
                                   [
                                     'Apache::Response',
                                     'Apache::RequestRec'
                                   ]
                                 ],
          'setup_client_block' => [
                                    [
                                      'Apache::RequestIO',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'short_name' => [
                            [
                              'Apache::Process',
                              'Apache::Process'
                            ]
                          ],
          'should_client_block' => [
                                     [
                                       'Apache::RequestIO',
                                       'Apache::RequestRec'
                                     ]
                                   ],
          'soak_end_container' => [
                                    [
                                      'Apache::Command',
                                      'Apache::Command'
                                    ]
                                  ],
          'some_auth_required' => [
                                    [
                                      'Apache::Access',
                                      'Apache::RequestRec'
                                    ]
                                  ],
          'special_list_call' => [
                                   [
                                     'ModPerl::Global',
                                     'ModPerl::Global'
                                   ]
                                 ],
          'special_list_clear' => [
                                    [
                                      'ModPerl::Global',
                                      'ModPerl::Global'
                                    ]
                                  ],
          'split' => [
                       [
                         'APR::Brigade',
                         'APR::Brigade'
                       ]
                     ],
          'start' => [
                       [
                         'APR::Bucket',
                         'APR::Bucket'
                       ]
                     ],
          'status' => [
                        [
                          'Apache::RequestRec',
                          'Apache::RequestRec'
                        ]
                      ],
          'status_line' => [
                             [
                               'Apache::RequestRec',
                               'Apache::RequestRec'
                             ]
                           ],
          'subprocess_env' => [
                                [
                                  'Apache::RequestRec',
                                  'Apache::RequestRec'
                                ]
                              ],
          'tag' => [
                     [
                       'APR::Pool',
                       'APR::Pool'
                     ]
                   ],
          'temp_pool' => [
                           [
                             'Apache::CmdParms',
                             'Apache::CmdParms'
                           ]
                         ],
          'test' => [
                      [
                        'APR::NetLib',
                        'APR::IpSubnet'
                      ]
                    ],
          'the_request' => [
                             [
                               'Apache::RequestRec',
                               'Apache::RequestRec'
                             ]
                           ],
          'thread_current' => [
                                [
                                  'APR::OS',
                                  'APR::OS'
                                ]
                              ],
          'timeout' => [
                         [
                           'Apache::Server',
                           'Apache::Server'
                         ]
                       ],
          'timeout_get' => [
                             [
                               'APR::Socket',
                               'APR::Socket'
                             ]
                           ],
          'timeout_set' => [
                             [
                               'APR::Socket',
                               'APR::Socket'
                             ]
                           ],
          'top_module' => [
                            [
                              'Apache::Module',
                              'Apache::Module'
                            ]
                          ],
          'trylock' => [
                         [
                           'APR::ThreadMutex',
                           'APR::ThreadMutex'
                         ]
                       ],
          'type' => [
                      [
                        'APR::Bucket',
                        'APR::Bucket'
                      ]
                    ],
          'unescape_url' => [
                              [
                                'Apache::URI',
                                'Apache'
                              ]
                            ],
          'unlock' => [
                        [
                          'APR::ThreadMutex',
                          'APR::ThreadMutex'
                        ]
                      ],
          'unparse' => [
                         [
                           'APR::URI',
                           'APR::URI'
                         ]
                       ],
          'unparsed_uri' => [
                              [
                                'Apache::RequestRec',
                                'Apache::RequestRec'
                              ]
                            ],
          'unset' => [
                       [
                         'APR::Table',
                         'APR::Table'
                       ]
                     ],
          'untaint' => [
                         [
                           'ModPerl::Util',
                           'ModPerl::Util'
                         ]
                       ],
          'update_mtime' => [
                              [
                                'Apache::Response',
                                'Apache::RequestRec'
                              ]
                            ],
          'uri' => [
                     [
                       'Apache::RequestRec',
                       'Apache::RequestRec'
                     ]
                   ],
          'used_path_info' => [
                                [
                                  'Apache::RequestRec',
                                  'Apache::RequestRec'
                                ]
                              ],
          'user' => [
                      [
                        'APR::URI',
                        'APR::URI'
                      ],
                      [
                        'Apache::RequestRec',
                        'Apache::RequestRec'
                      ]
                    ],
          'version' => [
                         [
                           'Apache::Module',
                           'Apache::Module'
                         ]
                       ],
          'walk_config' => [
                             [
                               'Apache::Directive',
                               'Apache::Directive'
                             ]
                           ],
          'wild_names' => [
                            [
                              'Apache::Server',
                              'Apache::Server'
                            ]
                          ],
          'write' => [
                       [
                         'Apache::RequestIO',
                         'Apache::RequestRec'
                       ]
                     ],
          'xlimited' => [
                          [
                            'Apache::CmdParms',
                            'Apache::CmdParms'
                          ]
                        ]
        };


use base qw(Exporter);

our @EXPORT = qw(print_method print_module print_object);

use constant MODULE => 0;
use constant OBJECT  => 1;

my $modules;
my $objects;

sub _get_modules {
    for my $method (sort keys %$methods) { 
        for my $item ( @{ $methods->{$method} }) {
            push @{ $modules->{$item->[MODULE]} }, [$method, $item->[OBJECT]];
        }
    }
}

sub _get_objects {
    for my $method (sort keys %$methods) { 
        for my $item ( @{ $methods->{$method} }) {
            push @{ $objects->{$item->[OBJECT]} }, [$method, $item->[MODULE]];
        }
    }
}

sub preload_all_modules {
    _get_modules() unless $modules;
    eval "require $_" for keys %$modules;
}

sub _print_func {
    my $func = shift;
    my @args = @_ ? @_ : @ARGV;
    no strict 'refs';
    print( ($func->($_))[0]) for @args;
}

sub print_module { _print_func('lookup_module', @_) }
sub print_object { _print_func('lookup_object', @_) }

sub print_method {
    my @args = @_ ? @_ : @ARGV;
    while (@args) {
         my $method = shift @args;
         my $object = (@args && 
             (ref($args[0]) || $args[0] =~ /^(Apache|ModPerl|APR)/))
             ? shift @args
             : undef;
         print( (lookup_method($method, $object))[0]);
    }
}

sub sep { return '-' x (shift() + 20) . "\n" }

# what modules contain the passed method.
# an optional object or a reference to it can be passed to help
# resolve situations where there is more than one module containing
# the same method.
sub lookup_method {
    my ($method, $object) = @_;

    unless (defined $method) {
        my $hint = "No 'method' argument was passed\n";
        return ($hint);
    }

    # strip the package name for the fully qualified method
    $method =~ s/.+:://;

    unless (exists $methods->{$method}) {
        my $hint = "Don't know anything about method '$method'\n";
        return ($hint);
    }

    my @items = @{ $methods->{$method} };
    if (@items == 1) {
        my $module = $items[0]->[MODULE];
        my $hint = "to use method '$method' add:\n" . "\tuse $module ();\n";
        return ($hint, $module);
    }
    else {
        if (defined $object) {
            my $class = ref $object || $object;
            for my $item (@items) {
                if ($class eq $item->[OBJECT]) {
                    my $module = $item->[MODULE];
                    my $hint = "to use method '$method' add:\n" .
                        "\tuse $module ();\n";
                    return ($hint, $module);
                }
            }
        }
        else {
            my %modules = map { $_->[MODULE] => 1 } @items;
            # remove dups if any (e.g. $s->add_input_filter and
            # $r->add_input_filter are loaded by the same Apache::Filter)
            my @modules = keys %modules;
            my $hint;
            if (@modules == 1) {
                $hint = "To use method '$method' add:\n\tuse $modules[0] ();\n";
                return ($hint, $modules[0]);
            }
            else {
                $hint = "There is more than one class with method '$method'\n" .
                    "try one of:\n" . join '', map {"\tuse $_ ();\n"} @modules;
                return ($hint, @modules);
            }
        }
    }
}

# what methods are contained in the passed module name
sub lookup_module {
    my ($module) = shift;

    unless (defined $module) {
        my $hint = "no 'module' argument was passed\n";
        return ($hint);
    }

    _get_modules() unless $modules;

    unless (exists $modules->{$module}) {
        my $hint = "don't know anything about module '$module'\n";
        return ($hint);
    }

    my @methods;
    my $max_len = 6;
    for ( @{ $modules->{$module} } ) {
        $max_len = length $_->[0] if length $_->[0] > $max_len;
        push @methods, $_->[0];
    }

    my $format = "%-${max_len}s %s\n";
    my $banner = sprintf($format, "Method", "Invoked on object type");
    my $hint = join '',
        ("\nModule '$module' contains the following XS methods:\n\n", 
         $banner,  sep(length($banner)),
         map( { sprintf $format, $_->[0], $_->[1]} @{ $modules->{$module} }),
         sep(length($banner)));

    return ($hint, @methods);
}

# what methods can be invoked on the passed object (or its reference)
sub lookup_object {
    my ($object) = shift;

    unless (defined $object) {
        my $hint = "no 'object' argument was passed\n";
        return ($hint);
    }

    _get_objects() unless $objects;

    # a real object was passed?
    $object = ref $object || $object;

    unless (exists $objects->{$object}) {
        my $hint = "don't know anything about objects of type '$object'\n";
        return ($hint);
    }

    my @methods;
    my $max_len = 6;
    for ( @{ $objects->{$object} } ) {
        $max_len = length $_->[0] if length $_->[0] > $max_len;
        push @methods, $_->[0];
    }

    my $format = "%-${max_len}s %s\n";
    my $banner = sprintf($format, "Method", "Module");
    my $hint = join '',
        ("\nObjects of type '$object' can invoke the following XS methods:\n\n",
         $banner, sep(length($banner)),
         map({ sprintf $format, $_->[0], $_->[1]} @{ $objects->{$object} }),
         sep(length($banner)));

    return ($hint, @methods);

}

1;
